# Generated by Django 4.1.1 on 2022-09-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
