# Generated by Django 4.1.1 on 2022-10-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_qna', '0003_alter_answer_user_alter_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
